<a href="https://colab.research.google.com/github/Rashed-2004/My_Python-Note-book/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**30**-**07**-***2025***

In [ ]:
#what is numpy ?
# numpy is core library for scientific computing in python
# what is the central object in numpy?
# numpy - Array's
# what is Numpy A?
# Arrays are high performence multile dimensional object which is design specially for mathmetical opreations
# Array's are order , immutable and allows duplicate data


In [ ]:
# How many type of data structures do we have in Numpy?
# There are three type
#1d --Array's --> Array's with zero columns and  specific rows(axis 0)
#2D--Array's --> Array's with both rows (axis 0) and columns (axis 1)
#3D --> also known as MultiDimensional

In [ ]:
# what are all use cases and mathematical operations acheived by using numpy?
"""1. Dot product /Inner product
   2. Matrix multiplication
   3. Element wise matrix multiplication
   4. solving the linear system
   5. inverse
   6. deteriment
   7. choose the random number
   8. statistics
   9. broadcasting method """


# Installation of Numpy

In [ ]:
! pip install numpy

In [ ]:
import numpy as np

In [ ]:
# check the vesrion of the numpy
np.__version__

'2.0.2'

# **Central object in numpy in Array's**

In [ ]:
# How can we create an array?
# Array's can be create from existing data
#1D--array's
a = np.array([1,2,3,4,5])
print(a)
# check the shape of the above array "a"
a.shape
# find the dimension of the array "a"
a.ndim
# find the number of the elements of the array "a"
a.size
# find the size in bytes occupied by each elemnet in above array's "a"
a.itemsize
# find the data type of the elemnts in above array
a.dtype

[1 2 3 4 5]


dtype('int64')

# Essential method in Numpy

In [ ]:
# access the element in the array
b = np.array([1,2,3])
# print the 2  from above array
print(b[1])
#reverse the entire array
print(b[ :: -1])


2
[3 2 1]


In [ ]:
# above array replace the "3" with "5"
b[2] = 5
print(b)

[1 2 5]


In [ ]:
#ARRAY --> ORDERD, IMMUTABLE AND ALLOWS THE DUPLICATES

*Element wise maths operation*

In [ ]:
c = np.array([2,0,3])
print(b+c)
# Note :- when we applying the arthematic operation on two array's the array's has to be in same length
# what is vector addition?
# when we apply addition on array of same length and dimenssions --> is known as Vector additions

[3 2 8]


In [ ]:
d = np.array ([5,6,7])
#find the sum of the elements of above array
print(d.sum())
# find the minimun element from the above array
print(d.min())
# find the maximum element from the above array
print (d.max())

18
5
7


In [ ]:
l = [1,2,3,4,5]
#create an array from the list
e = np.array(l)
print(e)
#add the 6 into above list
l.append(6)
print(l)

[1 2 3 4 5]
[1, 2, 3, 4, 5, 6]


In [ ]:
# how can we add the items into array?
# by creating "New array"

a1 = e + np .array([7])
print (a1)
"""when we add to single element array to the existing array with different size,
the new array  element is going to add with each element in the exsisting array this is known as boardcasting methods

[ 8  9 10 11 12]


In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array ([6,7,8,9,10])
arr3 = np.append(arr1,arr2)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# find the sqrt of each element in above arr1
print(np.sqrt(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]


# DOT PRODUCT

In [ ]:
a = np .array ([1,2])
b = np .array ([3,4])
dot = 0
for i in range (len(a)):
  dot += a[i] * b[i]
print(dot)

11


In [ ]:
# Define Dot product?
# vector multiplicstion of the array's and sum of elements of result
# multiply each coresponding element and do the sum
# Note :- when we applythe dot product the array's

In [ ]:
dot = np.dot(a,b)
print(dot)

11


In [ ]:
#Manual method
c =a*b
d =np.sum(c)
print(d)

11


In [ ]:
#another method
e = a.dot(b)
print(e)


11


31-07-2025

In [ ]:
import numpy as np
# create an array from set
s1 = {1,2,3,4,5}
a = np.array(s1)
print (type(a))
print(a)

<class 'numpy.ndarray'>
{1, 2, 3, 4, 5}


In [ ]:
t1 = (1,2,3,4,5)
b = np.array(t1)
print(b)

[1 2 3 4 5]


# 2D Array's

In [ ]:
a = np.array ([[1,2,3],[4,5,6]])
print(a)
#find the no of rows and columns
print(a.shape)
#find the dimensionality of an array
print(a.ndim)
#print the total elemnts in the array
print(a.size)
# print the size of the array
print (a.itemsize)
# print the data type of the arrays
print (a.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
8
int64


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
# how can we access the elements from the array
# print the entire 1st row
#syntax :- array[row_index,col_index]
print(a[0])
print(a[1])
print(a[1,1])
print(a[0,2])

[1 2 3]
[4 5 6]
5
3


In [ ]:
a = np.array([[1,2,3,4] ,[5,6,7,8,],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#print the values of 1st column in above array
print (a[ :,0])
# print the 3rd column values
print(a[:,2])

[1 5 9]
[ 3  7 11]


In [ ]:
#acess only 10 11 12
print(a[2,1:4])
#print the only 8 and 12
print (a[1:3,3])

[10 11 12]
[ 8 12]


In [ ]:
b = a[:,0]
for i in b:
  print(i)

1
5
9


# Transpose

In [ ]:
b = np.array([[1,2,3,4] ,[5,6,7,8,],[9,10,11,12]])
print(b)
print(b.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


# **Matrix Multiplication**

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[5,6]])
print(a@b)

[[13 16]
 [29 36]]


In [ ]:
#find the inverse of the array a?
d = np.linalg.inv(a)
print(d)


[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# how can i find the diagonal of an array a ?
e = np.diag(a)
print(e)


[1 4]


In [ ]:
# Note:- Diagonal on vector return a martix
c = np.diag([5,5,5])
print(c)

[[5 0 0]
 [0 5 0]
 [0 0 5]]


# Boolean Indexing

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#check the number which is more ten 2 and print True if more then 2 else print false
print(a>2)
#print the numbers
print(a[a>2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [ ]:
#np.where(logic,True, False)
a = np.array([[1,2],[3,4],[5,6]])
#print the number greater than 2 and less than number print it as a-1
b = np.where (a>2,a,-1)
print(b)

[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [ ]:
# compute the indexes where the conditio is true
c = np.array([10,19,20,30,41,50,61])
#get the inde position of the even numbers
even = np.argwhere(c%2==0).flatten()
print(even)

[0 2 3 5]


In [ ]:
even2 = np.argwhere(a%2==0)
print(even2)

[[0 1]
 [1 1]
 [2 1]]


# 01-08-2025

# Reshaping of an array

In [1]:
import numpy as np


In [2]:
# create a range of array up to 10
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
# print the range of numbers from 1 to 10
b = np.arange(1,11)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
# convert the array's "b" i  to 2 rows  and 5 colums
c = b.reshape(2,5)
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
# convert the array b into 5 rows and 2 colums
c = b.reshape(5,2)
print(c)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [13]:
# create a range of array from 1 to 6 and convert into 2 rows and 3 column
e = np.arange(1,7)
print(e)
f = e.reshape(2,3)
print(f)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [14]:
# what is the shape of e
print(e.shape)

(6,)


np.newaxis--> it is used change the data in certain manner

In [15]:
g = e[np.newaxis,:]
print(g)
print(g.shape)

[[1 2 3 4 5 6]]
(1, 6)


In [16]:
h = e[:,np.newaxis]
print(h)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


# **Concatenation**


In [18]:
# concatenation--> combine 2 array's or concatenate 2 array's
a = np.array([[1,2] ,[3,4]])
b = np.array([[5,6] ,[7,8]])
c = np.concatenate((a,b))
print(c)
# Note--1. when we give axis = 0 concatenate wrt rows wise, axis = 1 concatenate wrt columnwise
# when we give axis = None concatenate in 1D array format

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
d = np.concatenate((a,b.T), axis=1)
print(d)

[[1 2 5 7]
 [3 4 6 8]]


# **HSTACk**-->stack array insequence horizontal

In [20]:
#Hsatck:- stack array adding in sequence Horizontally
a = np.array([[1,2] ,[3,4]])
b = np.array([[5,6] ,[7,8]])
h = np.hstack((a,b))
print(h)

[[1 2 5 6]
 [3 4 7 8]]


# VSTACK--> stack arrays in sequence vertically

In [ ]:
#Vstack:- Stack array adding in sequence vertically

In [22]:
a = np.array([[1,2] ,[3,4]])
b = np.array([[5,6] ,[7,8]])
v = np.vstack((a,b))
print(v)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#  Broadcasting methods--> broadcasting is a powerful mechanism that allows numpy  to work with different arrays of different shapes when performing the arthamatic operation

In [24]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y = np.array([1,0,1])
z = x+y
print(z)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


# Copying of the Array's

In [25]:
a =np.array([1,2,3])
b = a
b [0] = 8
print(a)

[8 2 3]


In [29]:
a =np.array([1,2,3])
b = a.copy()
b [0] = 8
print(a)
print(b)

#Np.copy--> is used when we male any changes in the new array it won't impact on the original array's

[1 2 3]
[8 2 3]


# Generating Arrays

In [30]:
# generate an array's of zeros 2rows and 3 columns
a = np.zeros((2,3,))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [31]:
# generate an array's of zeros 2rows and 3 columns
a = np.zeros((2,3,))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [35]:
a=np.zeros(3)
print(a)

[0. 0. 0.]


In [32]:
# generate an array's of zeros 2rows and 3 columns
a = np.ones((2,3,))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [36]:
a=np.ones(3)
print(a)

[1. 1. 1.]


In [38]:
#generate an array's of specific number with particular rows and columns
d = np.full((3,3),2)
print(d)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [37]:
#generate an identity matrix
e =np.eye(4)
print(e)
#np.identity


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [39]:
e =np.identity(4)
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [47]:
#linspace:- splits the data into n equal parts
j = np.linspace(0,10,6)
print(j)

#np.linspace(start,end, NO of partitions)

[ 0.  2.  4.  6.  8. 10.]


# Random Numbers

In [58]:
#generate random numbers those are uniformly distributed from 0-1
a = np.random.random((3,2))
print(a)

[[0.21354509 0.81534787]
 [0.81699972 0.97572814]
 [0.05590441 0.89824729]]


In [62]:
#generate an array of random numbers with 1000 and find the mean and varience and std
c = np .random.randn(1000)
print(c.mean(),c.std(),c.var())
# How can we say the data is normally distributed--> when the mean of that is equals to 0 and satndard deviation = 1 the the normally distributed

-0.02117161103098961 0.9782014829150585 0.9568781411772195


In [74]:
##generate an array of integers from 3, 10 with 2rows and 3 columns
d =np.random.randint(3,10, size=(3,2))
print(d)


[[6]
 [4]
 [6]]


In [75]:
#generate an array of numbers upto 6 randomly with the size of 10
e = np.random.choice(7,size=10)
print(e)

[3 1 1 0 2 4 0 4 2 1]


In [76]:
import numpy as np
#x1 + x2 = 2200
#1.5x1 + 4x2 = 5050
#find the value of x1 and x2

a = np.array([[1,1],[1.5,4]])
b = np.array([2200,5050])
x = np.linalg.inv(a).dot(b)# slove(a,b)
print(x)
#AX =  B

[1500.  700.]


In [ ]:
"""
np.shape
np.size
np.ndim
np.dtype
np.itemsize
#what is 1d 2d and 3 d array's
# what is the diff b;w list and arrays
# How can we reshape an arrays--> np.reshape(row,col)--> 2d data
# How can we apply the dot product --> np.dot(ar1,ar2)
# How can we generate an array specific number --> np.full(ro,col),num)
# how can we copy an array--> np.copy()
#unifro distribution --> np.random.random
#how can you say a data is randomly distributed--> mean is zero, varience is equal to 1 and std is equal to 1
#random_numbers_with specific size--> np.random.choice(range of numbers,size=number)
#genrate range of random integers--> np.random.randint(start,end, size=(row,col))